### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by gobith** [svenvc/NeoNetworking#1]
Hello Sven,
I am trying out the example but got an error at the last part:

pharo:
2023-05-10 08:47:48.156 DIRQWW Read 
2023-05-10 08:47:48.157 DIRQWW Wrote {"method":"isPrime","error":"Invalid JSON"}
2023-05-10 08:47:48.157 DIRQWW Ending connection

telnet:
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

{"method":"isPrime","error":"Invalid JSON"}
Connection closed by foreign host.

Also somehow I need to press enter two times to see results in the pharo repl.
pharo>Gofer it url: 'github://svenvc/NeoNetworking'; package: 'Neo-Networking'; load. (enter enter)

a GoferLoad

Regards,
Georges

ps first time I see pharo in a repl, very nice :)

**Comment by svenvc** [comment]
Hi,

You entered an empty line, I think. The first log line says Read <nothing>. That is invalid, hence an error came back. I also see an empty line in you telnet session.

Concerning the NeoConsole REPL: yes you need to terminate input with an empty line, because multiline input is also possible (and very common). This is described when you say ask for help eval.

HTH,

Sven

**Comment by gobith** [comment]
Hello,

Yep my bad I had to enter a valid json string :) Sorry for that!

Georges
